######################################################################
# Automatically generated by qmake (2.01a) jue may 10 23:27:26 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += classImagen.h classPixel.h qcustomplot.h ventana.h vtn_propiedades.h \
    vtn_estirar.h \
	classFiltro.h \
    vtn_filtro.h
FORMS += ventana.ui vtn_propiedades.ui \
    vtn_estirar.ui \
    vtn_filtro.ui
SOURCES += classImagen.cpp \
           classPixel.cpp \
           main.cpp \
           qcustomplot.cpp \
           ventana.cpp \
           vtn_propiedades.cpp \
    vtn_estirar.cpp \
	classFiltro.cpp \
    vtn_filtro.cpp
RESOURCES += images.qrc
